#include "Serial.h"

#if SERIAL_HOWMANY > 2
#if defined(UART3_RTS_PIN) && defined(UART3_CTS_PIN)
UART _UART3_(UART3_TX_PIN, UART3_RX_PIN, UART3_RTS_PIN, UART3_CTS_PIN);
#else
UART _UART3_(UART3_TX_PIN, UART3_RX_PIN);
#endif
#endif

#if SERIAL_HOWMANY > 3
#if defined(UART4_RTS_PIN) && defined(UART4_CTS_PIN)
UART _UART4_(UART4_TX_PIN, UART4_RX_PIN, UART4_RTS_PIN, UART4_CTS_PIN);
#else
UART _UART4_(UART4_TX_PIN, UART4_RX_PIN);
#endif
#endif

#if SERIAL_HOWMANY > 4
#if defined(UART5_RTS_PIN) && defined(UART5_CTS_PIN)
UART _UART5_(UART5_TX_PIN, UART5_RX_PIN, UART5_RTS_PIN, UART5_CTS_PIN);
#else
UART _UART5_(UART5_TX_PIN, UART5_RX_PIN);
#endif
#endif