#include "Serial.h"

#if SERIAL_HOWMANY > 2
UART _UART3_(UART3_TX_PIN, UART3_RX_PIN);
#endif

#if SERIAL_HOWMANY > 3
UART _UART4_(UART4_TX_PIN, UART4_RX_PIN);
#endif

#if SERIAL_HOWMANY > 4
UART _UART5_(UART5_TX_PIN, UART5_RX_PIN, UART5_RTS_PIN, UART5_CTS_PIN);
#endif