#ifndef WIFI_S3_TYPES_H
#define WIFI_S3_TYPES_H

#define WL_SSID_MAX_LENGTH 32
#define WL_WPA_KEY_MAX_LENGTH 63
#define WL_WEP_KEY_MAX_LENGTH 13
#define WL_MAC_ADDR_LENGTH 6
#define WL_IPV4_LENGTH 4
#define WL_NETWORKS_LIST_MAXNUM	10
#define	MAX_SOCK_NUM 4
#define SOCK_NOT_AVAIL 255
#define NA_STATE -1
#define WL_MAX_ATTEMPT_CONNECTION 10

typedef enum {
   WL_NO_SHIELD = 255,
        WL_NO_MODULE = WL_NO_SHIELD,
        WL_IDLE_STATUS = 0,
        WL_NO_SSID_AVAIL,
        WL_SCAN_COMPLETED,
        WL_CONNECTED,
        WL_CONNECT_FAILED,
        WL_CONNECTION_LOST,
        WL_DISCONNECTED,
        WL_AP_LISTENING,
        WL_AP_CONNECTED,
        WL_AP_FAILED
} wl_status_t;

/* Encryption modes */
enum wl_enc_type {
    ENC_TYPE_WEP,
    ENC_TYPE_WPA,
    ENC_TYPE_TKIP = ENC_TYPE_WPA,
    ENC_TYPE_WPA2,
    ENC_TYPE_CCMP = ENC_TYPE_WPA2,
    ENC_TYPE_WPA2_ENTERPRISE,
    ENC_TYPE_WPA3,
    ENC_TYPE_NONE,
    ENC_TYPE_AUTO,

    ENC_TYPE_UNKNOWN = 255
};

#endif
